[[language]]
name = "rust"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "hyprlang"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
roots = ["pyproject.toml", "Poetry.lock", "."]
language-servers = ["pyright"]

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[language-server.docker-compose-langserver]
command = "docker-compose-langserver"
